user stories
chhoumann/p8 pull request #1
Opened 2023-02-16 10:18 UTC by chhoumann

- Setup
- Update user_stories.tex
- write preliminary to user stories

2023-02-16 13:36 UTC, TheRumle requested changes
We need to describe why we choose structured interview, what the benefits of user stories are, how we clarify conflicting elements and how we do it, how we refine user stories and how/why we do it.

2023-02-16 13:37 UTC, chhoumann commented
+ explain MoSCoW & add sources

2023-02-22 14:52 UTC, mkju19 approved these changes

2023-02-23 12:54 UTC, TheRumle approved these changes

2023-02-23 12:54 UTC, merged