Abstract
chhoumann/p8 pull request #97
Opened 2023-05-22 08:51 UTC by MrHonket

An abstract was written

2023-05-22 10:27 UTC, chhoumann requested changes
Considering something more formal

2023-05-22 11:09 UTC, TheRumle commented on report/src/setup/titlepages.tex
> +Using this app, we show that BLE with fingerprinting are suitable technique for presence detection.
The last point with glass panes and walls seems to not be significant for the project. We have not spent time trying to handle that, and it is not at all what we try to show with the experiment.

2023-05-22 13:42 UTC, chhoumann commented on report/src/setup/titlepages.tex
> +Using this app, we show that BLE with fingerprinting are suitable technique for presence detection.
```suggestion
This report presents an in-depth investigation into the application of Bluetooth Low Energy (BLE) and fingerprinting for presence detection.
The study commenced with an analysis phase to understand the needs of a company for presence detection, leading to the exploration of multiple localization technologies.
Among them, it was found that BLE, combined with fingerprinting, was a promising approach.
The research further delves into the transformation of this localization problem into a classification problem using a kNN-based algorithm.
A C\# application was developed to evaluate this method for occupancy classification.
The results of the evaluation demonstrates the efficacy of BLE and fingerprinting for reliable presence detection.
```

2023-05-23 07:14 UTC, Pattrigue approved these changes

2023-05-23 07:19 UTC, chhoumann approved these changes

2023-05-23 07:19 UTC, merged